### ISSUE TITLE
Send emails asynchronously making use of celery

### ISSUE THREAD

**Issue by Ajayneethikannan** [IMGIITRoorkee/omniport-service-emails#7]
In emails/actions change the email_push call to email_push.delay()
also add an __init__ file to the tasks folder so that celery can register the task

**Comment by ruddi10** [comment]
Would like to try it

**Comment by ShreyasTheOne** [comment]
I'd like to work on this issue

**Comment by pradumangoyal** [comment]
@algomaster99 Make sure this issue doesn't clash with your PR #9 that refines this repository according to the latest state.

**Comment by algomaster99** [comment]
@pradumangoyal haven't we tested that PR yet? I think it's pulled on production and works fine. Let's just merge it?

**Comment by pradumangoyal** [comment]
I would prefer if we can try a fresh setup instead. There are chances of having unstaged uncommitted changes in any other repository which can cause an issue.

**Comment by pradumangoyal** [comment]
@ShreyasTheOne Now you can take this up.
